name: "ğŸ› ï¸ - Run Generators Manually"

on:
  workflow_dispatch:

concurrency:
  group: action-generator-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: ğŸ… Checkout code
        uses: actions/checkout@v4

      - name: ğŸ… Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: ğŸ… Install Python dependencies
        run: python -m pip install -r requirements.txt --root-user-action=ignore

      - name: ğŸ… Generate themes JSON
        run: python tools/pipe-generateJson.py

      - name: ğŸ… Generate JSON files
        run: python tools/pipe-generateJsonFiles.py

      - name: ğŸ… Generate TXT files
        run: python tools/pipe-generateTxtFiles.py

      - name: ğŸ… Generate CSV
        run: python tools/pipe-generateCsv.py

      - name: ğŸ… Generate installers
        run: python tools/pipe-generateShFiles.py

      - name: ğŸ… Update themes in Gogh file
        run: python tools/pipe-updateThemes.py

      - name: ğŸ… Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: ğŸ… Generate WCAG reports
        run: deno run --allow-all tools/pipe-generateWcag.js
